# Generated by Django 2.1 on 2022-11-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('slave_id', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('activate_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'meter',
                'verbose_name_plural': 'meters',
            },
        ),
    ]
