# Generated by Django 2.1 on 2022-11-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('cdesc', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'control',
                'verbose_name_plural': 'controls',
            },
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_id',
            field=models.IntegerField(unique=True),
        ),
    ]
