# Generated by Django 2.1 on 2022-11-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221105_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='cdesc',
            new_name='desc',
        ),
    ]
